pip install numpy
pip install torch
pip install onnx
pip install onnx2c
pip install z3
pip install re
pip install onnxruntime   
pip install z3-solver
pip install pyyaml
pip install pandas 
pip install matplotlib
